;==========MODELLENDE==========;
[COSIMIR-Connections]
Input0=IOMonitor,CtrlCard1Exists,IFObject,CtrlCard1Exists
Input1=IOMonitor,CtrlCard2Exists,IFObject,CtrlCard2Exists
Input2=IOMonitor,CtrlCard3Exists,IFObject,CtrlCard3Exists
Input3=IOMonitor,CtrlCard4Exists,IFObject,CtrlCard4Exists
Input4=IOMonitor,CtrlCard5Exists,IFObject,CtrlCard5Exists
Input5=IOMonitor,CtrlCard6Exists,IFObject,CtrlCard6Exists
Input6=IOMonitor,CtrlCard7Exists,IFObject,CtrlCard7Exists
Input7=IOMonitor,CtrlCard8Exists,IFObject,CtrlCard8Exists

Input8=IFObject,CtrlCardSetActive,IOMonitor,CtrlCardSetActive
Input9=IOMonitor,CtrlCardIsActive,IFObject,CtrlCardIsActive
Input10=IFObject,CtrlCardSet16To31,IOMonitor,CtrlCardSet16To31
Input11=IOMonitor,CtrlCardIs16To31,IFObject,CtrlCardIs16To31

Input12=IFObject,IOMonitorIsActive,IOMonitor,IOMonitorIsActive
Input13=IOMonitor,IOMonitorIsActive,IOMonitor,IOMonitorIsActive
Input14=IOMonitor,PollingIsActive,IFObject,PollingIsActive

Input15=IOMonitor,CtrlCardIn0,IFObject,CtrlCardIn0
Input16=IOMonitor,CtrlCardIn1,IFObject,CtrlCardIn1
Input17=IOMonitor,CtrlCardIn2,IFObject,CtrlCardIn2
Input18=IOMonitor,CtrlCardIn3,IFObject,CtrlCardIn3
Input19=IOMonitor,CtrlCardIn4,IFObject,CtrlCardIn4
Input20=IOMonitor,CtrlCardIn5,IFObject,CtrlCardIn5
Input21=IOMonitor,CtrlCardIn6,IFObject,CtrlCardIn6
Input22=IOMonitor,CtrlCardIn7,IFObject,CtrlCardIn7
Input23=IOMonitor,CtrlCardIn8,IFObject,CtrlCardIn8
Input24=IOMonitor,CtrlCardIn9,IFObject,CtrlCardIn9
Input25=IOMonitor,CtrlCardIn10,IFObject,CtrlCardIn10
Input26=IOMonitor,CtrlCardIn11,IFObject,CtrlCardIn11
Input27=IOMonitor,CtrlCardIn12,IFObject,CtrlCardIn12
Input28=IOMonitor,CtrlCardIn13,IFObject,CtrlCardIn13
Input29=IOMonitor,CtrlCardIn14,IFObject,CtrlCardIn14
Input30=IOMonitor,CtrlCardIn15,IFObject,CtrlCardIn15
Input31=IOMonitor,CtrlCardIn16,IFObject,CtrlCardIn16
Input32=IOMonitor,CtrlCardIn17,IFObject,CtrlCardIn17
Input33=IOMonitor,CtrlCardIn18,IFObject,CtrlCardIn18
Input34=IOMonitor,CtrlCardIn19,IFObject,CtrlCardIn19

Input35=IFObject,CtrlCardOut0,IOMonitor,CtrlCardOut0
Input36=IFObject,CtrlCardOut1,IOMonitor,CtrlCardOut1
Input37=IFObject,CtrlCardOut2,IOMonitor,CtrlCardOut2
Input38=IFObject,CtrlCardOut3,IOMonitor,CtrlCardOut3
Input39=IFObject,CtrlCardOut4,IOMonitor,CtrlCardOut4
Input40=IFObject,CtrlCardOut5,IOMonitor,CtrlCardOut5
Input41=IFObject,CtrlCardOut6,IOMonitor,CtrlCardOut6
Input42=IFObject,CtrlCardOut7,IOMonitor,CtrlCardOut7
Input43=IFObject,CtrlCardOut8,IOMonitor,CtrlCardOut8
Input44=IFObject,CtrlCardOut9,IOMonitor,CtrlCardOut9
Input45=IFObject,CtrlCardOut10,IOMonitor,CtrlCardOut10
Input46=IFObject,CtrlCardOut11,IOMonitor,CtrlCardOut11
Input47=IFObject,CtrlCardOut12,IOMonitor,CtrlCardOut12
Input48=IFObject,CtrlCardOut13,IOMonitor,CtrlCardOut13
Input49=IFObject,CtrlCardOut14,IOMonitor,CtrlCardOut14
Input50=IFObject,CtrlCardOut15,IOMonitor,CtrlCardOut15

Input51=IOMonitor,CtrlCardSetOut0,IOMonitor,CtrlCardOut0
Input52=IOMonitor,CtrlCardSetOut1,IOMonitor,CtrlCardOut1
Input53=IOMonitor,CtrlCardSetOut2,IOMonitor,CtrlCardOut2
Input54=IOMonitor,CtrlCardSetOut3,IOMonitor,CtrlCardOut3
Input55=IOMonitor,CtrlCardSetOut4,IOMonitor,CtrlCardOut4
Input56=IOMonitor,CtrlCardSetOut5,IOMonitor,CtrlCardOut5
Input57=IOMonitor,CtrlCardSetOut6,IOMonitor,CtrlCardOut6
Input58=IOMonitor,CtrlCardSetOut7,IOMonitor,CtrlCardOut7
Input59=IOMonitor,CtrlCardSetOut8,IOMonitor,CtrlCardOut8
Input60=IOMonitor,CtrlCardSetOut9,IOMonitor,CtrlCardOut9
Input61=IOMonitor,CtrlCardSetOut10,IOMonitor,CtrlCardOut10
Input62=IOMonitor,CtrlCardSetOut11,IOMonitor,CtrlCardOut11
Input63=IOMonitor,CtrlCardSetOut12,IOMonitor,CtrlCardOut12
Input64=IOMonitor,CtrlCardSetOut13,IOMonitor,CtrlCardOut13
Input65=IOMonitor,CtrlCardSetOut14,IOMonitor,CtrlCardOut14
Input66=IOMonitor,CtrlCardSetOut15,IOMonitor,CtrlCardOut15

Input67=IOMonitor,CtrlCardOut0,IFObject,CtrlCardOut0
Input68=IOMonitor,CtrlCardOut1,IFObject,CtrlCardOut1
Input69=IOMonitor,CtrlCardOut2,IFObject,CtrlCardOut2
Input70=IOMonitor,CtrlCardOut3,IFObject,CtrlCardOut3
Input71=IOMonitor,CtrlCardOut4,IFObject,CtrlCardOut4
Input72=IOMonitor,CtrlCardOut5,IFObject,CtrlCardOut5
Input73=IOMonitor,CtrlCardOut6,IFObject,CtrlCardOut6
Input74=IOMonitor,CtrlCardOut7,IFObject,CtrlCardOut7
Input75=IOMonitor,CtrlCardOut8,IFObject,CtrlCardOut8
Input76=IOMonitor,CtrlCardOut9,IFObject,CtrlCardOut9
Input77=IOMonitor,CtrlCardOut10,IFObject,CtrlCardOut10
Input78=IOMonitor,CtrlCardOut11,IFObject,CtrlCardOut11
Input79=IOMonitor,CtrlCardOut12,IFObject,CtrlCardOut12
Input80=IOMonitor,CtrlCardOut13,IFObject,CtrlCardOut13
Input81=IOMonitor,CtrlCardOut14,IFObject,CtrlCardOut14
Input82=IOMonitor,CtrlCardOut15,IFObject,CtrlCardOut15
 
Input83=IOMonitor,CtrlCardOutIsDed0,IFObject,CtrlCardOutIsDed0
Input84=IOMonitor,CtrlCardOutIsDed1,IFObject,CtrlCardOutIsDed1
Input85=IOMonitor,CtrlCardOutIsDed2,IFObject,CtrlCardOutIsDed2
Input86=IOMonitor,CtrlCardOutIsDed3,IFObject,CtrlCardOutIsDed3
Input87=IOMonitor,CtrlCardOutIsDed4,IFObject,CtrlCardOutIsDed4
Input88=IOMonitor,CtrlCardOutIsDed5,IFObject,CtrlCardOutIsDed5
Input89=IOMonitor,CtrlCardOutIsDed6,IFObject,CtrlCardOutIsDed6
Input90=IOMonitor,CtrlCardOutIsDed7,IFObject,CtrlCardOutIsDed7
Input91=IOMonitor,CtrlCardOutIsDed8,IFObject,CtrlCardOutIsDed8
Input92=IOMonitor,CtrlCardOutIsDed9,IFObject,CtrlCardOutIsDed9
Input93=IOMonitor,CtrlCardOutIsDed10,IFObject,CtrlCardOutIsDed10
Input94=IOMonitor,CtrlCardOutIsDed11,IFObject,CtrlCardOutIsDed11
Input95=IOMonitor,CtrlCardOutIsDed12,IFObject,CtrlCardOutIsDed12
Input96=IOMonitor,CtrlCardOutIsDed13,IFObject,CtrlCardOutIsDed13
Input97=IOMonitor,CtrlCardOutIsDed14,IFObject,CtrlCardOutIsDed14
Input98=IOMonitor,CtrlCardOutIsDed15,IFObject,CtrlCardOutIsDed15

Input99=IOMonitor,IOMonitorState,IFObject,IOMonitorState

Input100=Gripper,Close,RV-2AJ,HCLOSE1
Input101=RV-2AJ,!HOPENED1,Gripper,Closed
Input102=RV-2AJ,HCLOSED1,Gripper,Closed


nInputs=103 
 
 
 
 
[COSIMIR-Program]
OUTPUT901=HOPEN1
OUTPUT902=HCLOSE1
OUTPUT903=HOPEN2
OUTPUT904=HCLOSE2
OUTPUT905=HOPEN3
OUTPUT906=HCLOSE3
OUTPUT907=HOPEN4
OUTPUT908=HCLOSE4
INPUT900=HOPENED1 , COSIMIR_CONTROL,-1,0
INPUT901=HCLOSED1 , COSIMIR_CONTROL,-1,0
INPUT902=HOPENED2 , COSIMIR_CONTROL,-1,0
INPUT903=HCLOSED2 , COSIMIR_CONTROL,-1,0
INPUT904=HOPENED3 , COSIMIR_CONTROL,-1,0
INPUT905=HCLOSED3 , COSIMIR_CONTROL,-1,0
INPUT906=HOPENED4 , COSIMIR_CONTROL,-1,0
INPUT907=HCLOSED4 , COSIMIR_CONTROL,-1,0
MultiPCROB=0,0,0,0
TimeIntervals=0.040000,0.040000,0.040000


[COSIMIR-ROPPV.DLL]
TOOLSWNDPOS=250 64
IO-CONFIG=IOMONIT.LVC
IO-CONFIGPOS=296 5 317 530 0 0 0.703419 -1 -1
IO-CONFIGSCALE=0.703419 -1 -1 4.740741 92661 151137 -300 -300
IOMonitor=0,427,8
IOMonitorType=0,401,1

						
	

[COSROP-Project]
COSIROPProjectJoints=5
COSIROPProjectAddJoints=0
COSIROPProjectHands=1
COSIROPProjectIOCards=1
COSIROPProjectInputs=0
COSIROPProjectOutputs=0
COSIROPProjectCreator=Kamil Zidek
COSIROPProjectCreatorSign=KZ
COSIROPProjectProgramName=test1
COSIROPProjectDescriptionLines=1
COSIROPProjectCommentLines=1
COSIROPProjectPrintSelection=4095
COSIROPProjectRobotType=RV-2AJ
COSIROPProjectDescription0=moj prvy program pre robota
COSIROPProjectComment0=eredgfgf
COSIROPProjectSupportLangType=8
COSIROPProjectSupportConType=0



[COSIMIR-Workcell]
DefaultLookat=fovy:400,hither:50,yon:10000,vx:2031,vy:1468,vz:-1969,rx:-115,ry:325,rz:142,twist:0
Displaymode=1,1,0,0,0,1,1,0,0

FramesPerSec=0

LMODEL=ambient:0.170743,0.170743,0.170743,localviewer:0.000000
LIGHT0=1,color:0.501961,0.501961,0.501961,pos:0,1,0,1
LIGHT1=1,color:0.752941,0.752941,0.752941,pos:0.57735,0.57735,0.57735,0
LIGHT2=1,color:0.752941,0.752941,0.752941,pos:0.578921,0.574195,-0.578921,0
LIGHT3=0,color:1,1,1,pos:0,1,0,0
LIGHT4=0,color:1,1,1,pos:0,1,0,0
LIGHT5=0,color:1,1,1,pos:0,1,0,0
LIGHT6=0,color:1,1,1,pos:0,1,0,0
LIGHT7=0,color:1,1,1,pos:0,1,0,0

LookatTrack=1,0
SimulationOptions=0.040000,1,0,1,1,1,0.200000,0.300000

Grid=x:1000,y:1000,nx:5,ny:5,mode:2,rgb:0,0,0,rgb:0,128,0,xPos:0,yPos:0,zPos:0
CoorSys=l:200,rgbX:255,0,0,rgbY:0,255,0,rgbZ:0,0,246,1,0,1,0,0,0,0,0,0,0
ColorSelObjects=rgb:0,255,0,rgb:0,0,0

GripWarnings=Grip:0,Release:0
TeachGripper=HCLOSE1
GripperName=GREIFER , Mitsubishi_Greifer
Conveyor=BANDLAUF , BANDENDE
BackgroundColor=rgb:255,255,224
DefaultLookatUp=fovy:400,hither:50,yon:10000,vx:2031,vy:1468,vz:-1969,rx:-115,ry:325,rz:142,twist:0,ux:0,uy:0,uz:1,asp:1,spw:0,eM:0,eD:70,pA:0
FullScreen=0,ChangeSettings:0,Width:640,Height:480,BitsPel:16,Freq:0
 


[COSIMIR-IRL]
Config=3,,C:\Program Files (x86)\COSIMIR Educational\BIN\
[COSIMIR-MRL]
Config=1,C:\Program Files (x86)\COSIMIR Educational\BIN\,,1








[COSIMIR-Flaechenkonvertierung]
MaxEdgeAngle=60.
EnableAtStart=TRUE
TakeAllObjects=TRUE








[COSIMIR]
OrientationRepresentation=2
Window1=9,1,0,641,328,1280,-1,-1,-1,-1,"Cvicenie1_zidek.POS"
WindowAttr1=1,44,208,388,520,668,784,22,0
Window2=3,1,0,0,525,640,-1,-1,-1,-1,"C:\USERS\LAB1\DOCUMENTS\Cvicenie1_zidek\Cvicenie1_zidek.MOD"
WindowAttr2=fovy:400,hither:50,yon:10000,vx:1730.24,vy:509.212,vz:-369.471,rx:94.098,ry:281.552,rz:51.556,twist:0,ux:0,uy:0,uz:1,asp:1,spw:0,eM:0,eD:70,pA:0
Window3=7,1,34,257,181,501,-1,-1,-1,-1,"Outputs"
WindowAttr3=2
Window4=7,1,34,11,181,255,-1,-1,-1,-1,"Inputs"
WindowAttr4=1
nWindows=6
1_32=C:\USERS\LAB1\DOCUMENTS\Cvicenie1_zidek\Cvicenie1_zidek.MB4
1=C:\USERS\LAB1\DOCUME~1\CVICEN~1\CVICEN~1.MB4
1FileType=508
2_32=C:\USERS\LAB1\DOCUMENTS\Cvicenie1_zidek\Cvicenie1_zidek.IRD
2=C:\USERS\LAB1\DOCUME~1\CVICEN~1\CVICEN~1.IRD
2FileType=0
3_32=C:\USERS\LAB1\DOCUMENTS\Cvicenie1_zidek\Cvicenie1_zidek.POS
3=C:\USERS\LAB1\DOCUME~1\CVICEN~1\CVICEN~1.POS
3FileType=0
Window5=14,1,526,0,657,640,-1,-1,-1,-1,"Messages"
WindowAttr5=Messages
Window6=10,1,329,641,657,1280,-1,-1,-1,-1,"Cvicenie1_zidek.MB4"
WindowAttr6=1,0,508

[COSIMIR-COSACT]
NrOfActions=0
[COSIMIR-MCONF]
LevelOfDetail=0
[COSIMIR-MVIS]
VisConveyors=mark:0,size:1.000000,color:255
VisPolyPoints=mark:1,size:10.000000,color:16711680
VisGrippers=mark:1,size:40.000000,color:255
VisGrippoints=mark:1,size:40.000000,color:65280
VisBoundingBox=mark:1,size:10.000000,color:55295
VisVertices=mark:1,size:10.000000,color:16711680,markall:0,savenormals:1
2DEditor=mark:1,size:10.000000,size:10,axes:200.000000
VisMeasureTool=mark:1,color:8388608
Vis3DCursor=csedit:0,csview:0
VisGrid=show:0,size:100.000000,color:55295,teach:0,xdim:1000.000000,ydim:1000.000000,zdim:1000.000000,xorigin:-500.000000,yorigin:-500.000000,zorigin:0.000000
EditMode=0
[COSIMIR-MLib]
HidePic=0
NoAutoAttach=0
NoAutoExchangeRobot=0
MLibDlg=0
[COSIMIR-Projects]
RV-2AJ=1
1=.\Cvicenie1_zidek.PRJ
[RENSORT.DLL]
Programs=10,10
Poslists=1,1
Editor Parameters=0,0,Fixedsys,9,4
[COSIMIR-MEXPL]
MExplOpen=0
[COSIMIR-MPROP]
MPropOpen=0
[COSIMIR-MELEM]
EnvRestart=0
[Kollisionserkennung]
collActive=False
showSelectedObjects=False
showUnselectedObjects=False
showCollidedObjects=True
showFullSection=False
colorOfSelectedArea=(  0, 255, 255)
colorOfSelectedEdge=(  0,   0, 255)
colorOfUnselectedArea=(128, 128, 128)
colorOfUnselectedEdge=(  0,   0,   0)
colorOfCollidedArea=(255,   0, 128)
colorOfCollidedEdge=(255,   0,   0)
collisionMessages=None
checkAgainstAll=False
collisionInObjects=False
collisionByGrip=False
minCollisionDistance=0.000
nSelectedObjects=0
[COSIMIR-LOOKAT]
LookAtCfgDlg=0
LookAtOn=0
OneCycle=0
RecFrame=0
WithFrame=0
AVISpeed=30
EveryPic=1
SetLookAtDlg=0
[COSTEX]
TexMapOn=0
TexPar=0,0,0,0,0,1,1
[COSIMIR-Sensor]
SensorDisp=1,1,,255,65280
[COSIMIR-Alias-Objects]
nAliasObjects=1
AliasObject0=WORKSPACE,0,1
[COSIMIR-IRDATA]
Config=0,0,1
[COSIMIR-BAPS]
Config=0,0,C:\Program Files (x86)\COSIMIR Educational\BIN\,
[Tchgui_Window_Position]
Pos=4294967294 1 0 0 0 0 880 365 1206 631 2 0 2.000000 0.000000 0.000000
